# Generated by Django 3.2.7 on 2021-09-19 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_nid', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nid', models.IntegerField(default=0)),
                ('node_name', models.CharField(max_length=200)),
                ('node_desc', models.CharField(max_length=200)),
                ('read_only', models.BooleanField()),
                ('parent_id', models.IntegerField(default=0)),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='node.tree')),
            ],
        ),
    ]
