# Generated by Django 3.2.7 on 2021-09-21 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0002_auto_20210920_0553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='node_desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='node',
            old_name='node_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='node',
            old_name='parent_id',
            new_name='parent',
        ),
    ]
